### PR TITLE
Download tar instead of zip archive when installing nerd-fonts.

### PR DESCRIPTION
**Pull request by meinzer1899**
In release v3.0.2 (https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2), the release archives are also provided as .tar.xz which results in a size decrease of ~90%. zi can handle both tar and zip archives.

### CODE REVIEW

**Comment by meinzer1899** [comment]
@ reviewer:
- [ ] is it possible to extract the .ttf to a directory in /fonts which matches the font name, e.g. `.../font/Meslo` with using the *id* from `id-as` like this

```shell
zi ice if"[[ -d ${HOME}/.fonts/ttf ]] && [[ $OSTYPE = linux* ]]" \
  .....
  atclone="rm -f *Windows*; mv -vf *.ttf ${HOME}/.fonts/ttf/${id}; fc-cache -v -f" atpull"%atclone"
  .....
```
instead of
```shell
   atclone="rm -f *Windows*; mv -vf *.ttf ${HOME}/.fonts/ttf; fc-cache -v -f" atpull"%atclone"
```

**Comment by ss-o** [comment]
@meinzer1899 I will do triage and update you on this :+1:

**Comment by ss-o** [comment]
After trying out multiple scenarios, I concluded that the install command becomes long and complex. From user feedback and related conversations, it became clear that Zi is over-engineered and has become too complex for the majority. I think the best route to continue is to simplify and promote the creation of [Zsh plugins](https://wiki.zshell.dev/ecosystem/category/%EF%B8%8F-plugins), [Zi annexes](https://wiki.zshell.dev/ecosystem/category/-annexes) and [Zi packages](https://wiki.zshell.dev/ecosystem/category/-packages). This is relatively easy, super flexible, and can be used/improved by others.

I think the best approach for installing fonts would be to create an annex, which would allow an easy, reliable, and flexible way to install fonts. Users would be able to install the font(s) using an annex with `atclone`, `atpull`, `atinit`, and `atload` hooks, which would do the rest when it is required and what is required. For example, the installation of fonts would look like this: 

```sh
zi font'Meslo'
zi light z-shell/0
```

What's your opinion on this?

**Comment by ss-o** [comment]
Pull Request closed and locked due to lack of activity. If you'd like to build on this closed PR, you can clone it using this method: https://stackoverflow.com/a/14969986 Then open a new PR, referencing this closed PR in your message.

**Pull request closed without merging**
