### PR TITLE
[feat]: theme update

### LINKED ISSUE #83: [docs]: include asciinema video for sbin ice-modifier
```
<!-- TODO: Below can be replaced with asciinema video (commands to replicate the next NOTE comment) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L108

### LINKED ISSUE #84: [docs]: Below can be replaced with detailed asciinema video (to the next NOTE comment) -->
```
<!-- TODO: Below can be replaced with a detailed asciinema video (to the next NOTE comment) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L48

### LINKED ISSUE #85: [docs]: include asciinema video for fbin ice-modifier
```
<!-- TODO: [docs]: Below exmaple can be replaced with asciinema image (GIF) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md#L161

### LINKED ISSUE #86: [docs]: include asciinema for gem ice-modifier
```
<!-- TODO: [docs]: Below exmaple can be replaced with asciinema image (GIF) -->
```
https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L192

### LINKED ISSUE #87: [docs]: include asciinema video for fsrc and ferc ice-modifiers
```
<!-- TODO: [docs]: Below exmaple can be replaced with asciinema image (GIF) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L307

### LINKED ISSUE #88: [docs]: include asciinema video for fmod ice-modifier
```
<!-- TODO: [docs]: Below exmaple can be replaced with asciinema image (GIF) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L268

### LINKED ISSUE #89: [docs]: include asciinema video for pip ice-modifier
```
<!-- TODO: [docs]: Below exmaple can be replaced with asciinema image (GIF) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L241

### LINKED ISSUE #90: [docs]: include asciinema video for node ice-modifier
```
<!-- TODO: [docs]: Below exmaple can be replaced with asciinema image (GIF) -->
```

https://github.com/z-shell/wiki/blob/3b250cea54de117e23d0998d5416614e3fa7de0c/ecosystem/annexes/1_bin_gem_node.md?plain=1#L215

### PR DESCRIPTION
**Pull request by ss-o**

### CODE REVIEW

**Review by 0xMRTT — APPROVED** [review]
I think that tabs are better.

Antigen is maybe a [dead](https://github.com/zsh-users/antigen/issues/725) project. We can replace it by one of his successor or remove it or keep it 😉.

Otherwise all seems to be good 🙂

**Comment by ss-o** [comment]
> I think that tabs are better.
> 
> Antigen is maybe a [dead](https://github.com/zsh-users/antigen/issues/725) project. We can replace it by one of his successor or remove it or keep it wink.
> 
> Otherwise all seems to be good slightly_smiling_face

We can it remove if it seems dead, and the community can propose what to add, so if you have a project you like, propose it.

**Comment by 0xMRTT** [comment]
After antigen there is antibody (dead). 

The successor is antidote
https://github.com/mattmc3/antidote and there is an issue about the migration from antigen to antidote: https://github.com/mattmc3/antidote/issues/31

Website of antidote: https://getantidote.github.io/

We can add this in a new PR. So, merge this one and 'll create a new one for removing antigen

**Comment by ss-o** [comment]
Then need to use sourcegraph to find all "antigen" mentions and replace/remove them accordingly. With sourcegrapth it is easy to find and clean fully.

**Comment by 0xMRTT** [comment]
🎉🎉🎉🎉

**Pull request merged**
