### PR TITLE
New Crowdin translations by Github Action

### PR DESCRIPTION
**Pull request by ss-o**
CodeSandbox logoCodeSandbox logo&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/z-shell/wiki/l10n_crowdin_action?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=z-shell&repo=wiki&branch=l10n_crowdin_action">VS Code</a>

### CODE REVIEW

**Review by ss-o — COMMENTED** [review]
Nice :1st_place_medal:

**Comment by 0xMRTT** [comment]
I think it's corrected now ?

**Comment by 0xMRTT** [comment]
I've also reached 26%

**Comment by ss-o** [comment]
I think you use/view  GitHub with some missing features because you are always not responding and asking for specific areas such as file diffs/conversions, which are usually viewed in the same conversation on a PR.

**Comment by 0xMRTT** [comment]
> I think you use/view GitHub with some missing features because you are always not responding and asking for specific areas such as file diffs/conversions, which are usually viewed in the same conversation on a PR.

If I not responding is maybe because I don't have notifications for GitHub and if I ask is because I see GitHub on mobile 😔😅. But I will enable notifications 🙂

**Pull request merged**
